#+title: Readme


* About this repository

I just built this repository as a revision to my course in data algorithms


* How to compile and execute the test

To compile, you do it as a normal compilation but you will need to add *-lgtest* as a compilation flag

The *google test* package need to be downloaded.


Example of compilation :

#+begin_example
g++ Stack.cpp Stack_test.cpp -o Stack -lgtest
#+end_example

A binary called Stack will be generated.


* Compilation using Makefile

Compilation using makefile is pretty simple.
You should be in the *root location* of the folder.

Then you can run make with *Queue, LinkedList, ...* (whatever you want to compile)

Example : Compile and run Heap tests
#+begin_example
make Heap
#+end_example

* Explanation of smart pointers auto deallocation functions

- Smart pointers are supposed to be deallocated automatically but the size of the stack provoke deallocation issues
with the different data structures because they each them contains reference to an other (the next one).

- You can confirm this behavior by running insertion of multiple data and delete the destructors that I have created.

- The solution to this behavior is to change ownership of all the pointers to a unique one that will be deallocated at the end
of the scope of the destructor function.

